################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/can.c \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/cpu.c \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/flash.c \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/nvm.c \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/timer.c \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/uart.c \
/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/usb.c 

OBJS += \
./core/ARMCM4_STM32F3/can.o \
./core/ARMCM4_STM32F3/cpu.o \
./core/ARMCM4_STM32F3/flash.o \
./core/ARMCM4_STM32F3/nvm.o \
./core/ARMCM4_STM32F3/timer.o \
./core/ARMCM4_STM32F3/uart.o \
./core/ARMCM4_STM32F3/usb.o 

C_DEPS += \
./core/ARMCM4_STM32F3/can.d \
./core/ARMCM4_STM32F3/cpu.d \
./core/ARMCM4_STM32F3/flash.d \
./core/ARMCM4_STM32F3/nvm.d \
./core/ARMCM4_STM32F3/timer.d \
./core/ARMCM4_STM32F3/uart.d \
./core/ARMCM4_STM32F3/usb.d 


# Each subdirectory must supply rules for building sources it contributes
core/ARMCM4_STM32F3/can.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/can.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/can.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/ARMCM4_STM32F3/cpu.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/cpu.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/cpu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/ARMCM4_STM32F3/flash.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/ARMCM4_STM32F3/nvm.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/nvm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/nvm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/ARMCM4_STM32F3/timer.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/timer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/timer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/ARMCM4_STM32F3/uart.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/ARMCM4_STM32F3/usb.o: /Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Source/ARMCM4_STM32F3/usb.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/ARMCM4_STM32F3/usb.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

