################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
S_SRCS += \
../startup_stm32f303xc.s 

C_SRCS += \
../hooks.c \
../led.c \
../main.c \
../usbd_bulk.c \
../usbd_conf.c \
../usbd_desc.c 

OBJS += \
./hooks.o \
./led.o \
./main.o \
./startup_stm32f303xc.o \
./usbd_bulk.o \
./usbd_conf.o \
./usbd_desc.o 

C_DEPS += \
./hooks.d \
./led.d \
./main.d \
./usbd_bulk.d \
./usbd_conf.d \
./usbd_desc.d 


# Each subdirectory must supply rules for building sources it contributes
hooks.o: ../hooks.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"hooks.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
led.o: ../led.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"led.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
main.o: ../main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
%.o: ../%.s
	arm-none-eabi-gcc -mcpu=cortex-m4 -g3 -DSTM32F303xC -c -x assembler-with-cpp --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
usbd_bulk.o: ../usbd_bulk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usbd_bulk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
usbd_conf.o: ../usbd_conf.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usbd_conf.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
usbd_desc.o: ../usbd_desc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F303xC -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -c -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source -I/Users/bigfede/Documents/Repository/squadraCorse/SC19/TLBoard/Software/openBLT/Source/ARMCM4_STM32F3 -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/CMSIS/Device/ST/STM32F3xx/Include" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32F3xx_HAL_Driver/Inc/Legacy" -I"/Users/bigfede/Documents/Repository/squadraCorse/SC19/DashBoard/Software/openBLT/Demo/ARMCM4_STM32F3_Discovery_F303VC_TrueStudio/Boot/lib/STM32_USB_Device_Library/Core/Inc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usbd_desc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

